name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@master
    # - name: Get release version
    #   id: get_version
    #   run: echo "RELEASE_VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
    # - name: Publish to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: emcniece/dockeryourxyzzy
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     tags: "latest,${{ env.RELEASE_VERSION }}"
    # - name: Docker Hub Description
    #   uses: peter-evans/dockerhub-description@v2
    #   env:
    #     DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #     DOCKERHUB_REPOSITORY: emcniece/dockeryourxyzzy

  Normal:
      runs-on: ubuntu-latest
      steps:
      # - name: Login To GitHub
      #   run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Login to Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} |  docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - uses: actions/checkout@v2

      - name: Setup ENV
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
      
      - name: Normal
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          file: Dockerfile
          tags: |
            emcniece/dockeryourxyzzy:${{ env.VERSION }}
#            ghcr.io/emcniece/dockeryourxyzzy:${{ env.VERSION }}
            emcniece/dockeryourxyzzy:latest
#            ghcr.io/emcniece/dockeryourxyzzy:latest
      
      - name: Prebuilt
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          file: Dockerfile.built
          tags: |
            emcniece/dockeryourxyzzy:${{ env.VERSION }}-built
#            ghcr.io/emcniece/dockeryourxyzzy:${{ env.VERSION }}-built
